environment:
  ENV: production
packages:
  - name: tweets
    actions:
      - name: get_tweets
        runtime: 'nodejs:default'
        main: main ## Function name
        limits:
          timeout: 3500
          memory: 128
